<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVdgz8Cu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVdgz8Cu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVdgz8Cu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVdgz8Cu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVdgz8Cu\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vdgz8Cu',
    'container.build_id' => '1d69f49f',
    'container.build_time' => 1629208747,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVdgz8Cu');
