<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYNNJ8nR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYNNJ8nR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYNNJ8nR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYNNJ8nR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYNNJ8nR\App_KernelDevDebugContainer([
    'container.build_hash' => 'YNNJ8nR',
    'container.build_id' => '953a76cf',
    'container.build_time' => 1629203623,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYNNJ8nR');
