<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVqbRyez\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVqbRyez/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVqbRyez.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVqbRyez\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVqbRyez\App_KernelDevDebugContainer([
    'container.build_hash' => 'VqbRyez',
    'container.build_id' => 'f4ec116d',
    'container.build_time' => 1624626121,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVqbRyez');
